### PR TITLE
fixed graph, added filtering, fixed navigation tabs

### PR DESCRIPTION
**Pull request by jameBroa**
Changed library for graph on stats page.
Finished implementing parsing logic
Finishing implementing filtering logic
Note: filtering logic in stats.js can be simplified but too lazy to do it.

Finished styling Tabs

### CODE REVIEW

**Review by bvechiato — APPROVED** [review]

**Review by jameBroa — COMMENTED** [review]
changes fine

**Comment by bvechiato** [comment]
I reviewed but it won't let me merge???

**Comment by jameBroa** [comment]
> I reviewed but it won't let me merge???

i think we can close this pr. the last merge i did was a more updated version than this one

**Comment by bvechiato** [comment]
ok cool

**Pull request closed without merging**
